# Stubs for hqlib.report (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .report import QualityReport as QualityReport
from .section import Section as Section
