# Stubs for hqlib.metric_source.owasp_dependency_report.jenkins_owasp_dependency_plugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..abstract import owasp_dependency_report
from ..ci_server.jenkins import Jenkins
from typing import Any, List

class JenkinsOWASPDependencyReport(owasp_dependency_report.OWASPDependencyReport, Jenkins):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_dependencies_info(self, metric_source_id: str, priority: str) -> list: ...
    def metric_source_urls(self, *job_names: str) -> List[str]: ...
