# Stubs for hqlib.metric_source.owasp_dependency_report.owasp_dependency_xml_report (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...typing import DateTime
from ..abstract import owasp_dependency_report
from typing import Any, List

class OWASPDependencyXMLReport(owasp_dependency_report.OWASPDependencyReport):
    def __init__(self, **kwargs: Any) -> None: ...
    def get_dependencies_info(self, metric_source_id: str, priority: str) -> List: ...
    def metric_source_urls(self, *report_urls: str) -> List[str]: ...
