# Stubs for hqlib.metric_source.owasp_dependency_report.tfs_owasp_dependency_xml_report (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...typing import DateTime
from .owasp_dependency_xml_report import OWASPDependencyXMLReport
from typing import Any

def tfs_metric_source_id_decorator(func: Any): ...

class TfsOWASPDependencyXMLReport(OWASPDependencyXMLReport):
    def __init__(self, base_url: str, organization: str, project: str, definitions: str, pat_token: str, **kwargs: Any) -> None: ...
    def get_dependencies_info(self, metric_source_id: str, priority: str) -> list: ...
