# Stubs for hqlib.configuration.configuration (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..domain import Project

def project(project_folder_or_filename: str) -> Project: ...
