# Stubs for hqlib.requirement (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .document import TrackDocumentAge as TrackDocumentAge
from .environment import OpenVAS as OpenVAS, TrackCIJobs as TrackCIJobs, TrackSonarVersion as TrackSonarVersion
from .process_quality import PredictUserStories as PredictUserStories, TrackActions as TrackActions, TrackBugs as TrackBugs, TrackDurationOfUserStories as TrackDurationOfUserStories, TrackFindings as TrackFindings, TrackManualLTCs as TrackManualLTCs, TrackQualityGate as TrackQualityGate, TrackReadyUS as TrackReadyUS, TrackRisks as TrackRisks, TrackSecurityAndPerformanceRisks as TrackSecurityAndPerformanceRisks, TrackSecurityBugs as TrackSecurityBugs, TrackSecurityTestDate as TrackSecurityTestDate, TrackStaticSecurityBugs as TrackStaticSecurityBugs, TrackTechnicalDebt as TrackTechnicalDebt, TrackUserStoriesInProgress as TrackUserStoriesInProgress, UserStoriesAndLTCs as UserStoriesAndLTCs
from .product_quality import ART as ART, ARTCoverage as ARTCoverage, Accessibility as Accessibility, AggregatedTestCoverage as AggregatedTestCoverage, Checkmarx as Checkmarx, CodeQuality as CodeQuality, OJAuditViolations as OJAuditViolations, OWASPDependencies as OWASPDependencies, OWASPZAP as OWASPZAP, PerformanceEndurance as PerformanceEndurance, PerformanceLoad as PerformanceLoad, PerformanceScalability as PerformanceScalability, TrackBranches as TrackBranches, TrustedProductMaintainability as TrustedProductMaintainability, UnitTestCoverage as UnitTestCoverage, UnitTests as UnitTests, ViolationsBySeverity as ViolationsBySeverity, ViolationsByType as ViolationsByType
from .sonar import CSharp as CSharp, Java as Java, JavaScript as JavaScript, Python as Python, TypeScript as TypeScript, VisualBasic as VisualBasic, Web as Web
from .team import TrackSpirit as TrackSpirit
