# Stubs for hqlib.requirement.document (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..domain import Requirement

class TrackDocumentAge(Requirement): ...
