# Stubs for hqlib.metric_source.file.file_with_date (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from hqlib import domain
from hqlib.typing import DateTime
from typing import Any

class FileWithDate(domain.MetricSource):
    metric_source_name: str = ...
    def __init__(self, **kwargs: Any) -> None: ...
    def get_datetime_from_content(self, url: str) -> DateTime: ...
