# Stubs for git.refs.remote (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .head import Head
from typing import Any, Optional

class RemoteReference(Head):
    @classmethod
    def iter_items(cls, repo: Any, *args: Any, **kwargs: Any): ...
    @classmethod
    def delete(cls, repo: Any, *refs: Any, **kwargs: Any) -> None: ...
    @classmethod
    def create(cls, *args: Any, **kwargs: Any) -> None: ...
