# Stubs for git.refs.tag (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .reference import Reference
from git.objects.commit import Commit
from git.objects.tag import TagObject
from typing import Any, Optional

class TagReference(Reference):
    commit: Commit = ...
    @property
    def tag(self) -> Optional[TagObject]: ...
    object: Any = ...
    @classmethod
    def create(cls, repo: Any, path: Any, reference: str = ..., force: bool = ..., **kwargs: Any): ...
    @classmethod
    def delete(cls, repo: Any, *tags: Any) -> None: ...
Tag = TagReference
