# Stubs for hqlib.persistence (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .json_persister import FilePersister as FilePersister, JsonPersister as JsonPersister
