# Stubs for hqlib.persistence.json_persister (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Dict, List, Union

class JsonPersister:
    @classmethod
    def read_json(cls: Any, location: str) -> Dict[str, Union[str, List, Dict]]: ...
    @classmethod
    def write_json(cls: Any, document: Dict, location: str) -> Any: ...

class FilePersister(JsonPersister):
    @classmethod
    def read_json(cls: Any, location: str) -> Dict[str, Union[str, List, Dict]]: ...
    @classmethod
    def write_json(cls: Any, document: Dict, location: str) -> Any: ...
