# Stubs for hqlib.metric_source.coverage_report.html_coverage_report (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...metric_source import url_opener
from ..abstract.coverage_report import CoverageReport
from hqlib.typing import DateTime
from typing import Any

class HTMLCoverageReport(CoverageReport):
    def __init__(self, **kwargs: Any) -> None: ...
    def statement_coverage(self, metric_source_id: str) -> float: ...
    def branch_coverage(self, metric_source_id: str) -> float: ...
    def datetime(self, *metric_source_ids: str) -> DateTime: ...
