# Stubs for hqlib.metric_source.coverage_report.jacoco (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .html_coverage_report import HTMLCoverageReport

class JaCoCo(HTMLCoverageReport):
    metric_source_name: str = ...
