# Stubs for hqlib.metric.product.performance.base_performance_metric (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from hqlib import domain
from hqlib.typing import MetricValue

class PerformanceMetricMixin(domain.Metric):
    def value(self) -> MetricValue: ...
