# Stubs for hqlib.metric_source.test_report.robot_framework_test_report (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...typing import DateTime
from ..abstract import test_report
from ..url_opener import UrlOpener
from typing import List

class RobotFrameworkTestReport(test_report.TestReport):
    metric_source_name: str = ...
    def metric_source_urls(self, *report_urls: str) -> List[str]: ...
