# Stubs for hqlib.metric_source.test_report.uft_test_report (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...typing import DateTime
from ..abstract import test_report
from ..url_opener import UrlOpener

class UFTTestReport(test_report.TestReport):
    metric_source_name: str = ...
