# Stubs for hqlib.filesystem (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import pathlib
from typing import Any, Union

PathType = Union[str, pathlib.Path]

class FileSystem:
    @staticmethod
    def write_file(contents: str, filename: PathType, mode: str, encoding: str=...) -> None: ...
    @staticmethod
    def create_dir(dir_name: PathType) -> None: ...
    @staticmethod
    def make_file_readable(filename: PathType) -> None: ...

write_file: Any
create_dir: Any
