# Stubs for hqlib.log (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import logging

class SuppressRepeatMessages(logging.Filter):
    def __init__(self) -> None: ...
    def filter(self, record: logging.LogRecord) -> bool: ...

def init_logging(log_level: str) -> None: ...
