# Stubs for github (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .MainClass import Github as Github, GithubIntegration
from .GithubException import BadAttributeException, BadCredentialsException, BadUserAgentException, GithubException, RateLimitExceededException, TwoFactorException, UnknownObjectException
from .InputFileContent import InputFileContent
from .InputGitAuthor import InputGitAuthor
from .InputGitTreeElement import InputGitTreeElement

def enable_console_debug_logging() -> None: ...
