# Stubs for github.AuthorizationApplication (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class AuthorizationApplication(github.GithubObject.CompletableGithubObject):
    @property
    def name(self): ...
    @property
    def url(self): ...
