# Stubs for github.CommitStats (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class CommitStats(github.GithubObject.NonCompletableGithubObject):
    @property
    def additions(self): ...
    @property
    def deletions(self): ...
    @property
    def total(self): ...
