# Stubs for github.Consts (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

REQ_IF_NONE_MATCH: str
REQ_IF_MODIFIED_SINCE: str
PROCESSING_202_WAIT_TIME: int
RES_ETAG: str
RES_LAST_MODIFIED: str
headerRateLimit: str
headerRateRemaining: str
headerRateReset: str
headerOAuthScopes: str
headerOTP: str
defaultMediaType: str
mediaTypeStarringPreview: str
mediaTypeImportPreview: str
mediaTypeReactionsPreview: str
mediaTypeIntegrationPreview: str
mediaTypeProjectsPreview: str
mediaTypeCommitSearchPreview: str
mediaTypeBlockUsersPreview: str
mediaTypeTopicsPreview: str
mediaTypeLabelDescriptionSearchPreview: str
mediaTypeLockReasonPreview: str
mediaTypeOrganizationInvitationPreview: str
mediaTypeRequireMultipleApprovingReviews: str
mediaTypeMigrationPreview: str
highLightSearchPreview: str
signaturesProtectedBranchesPreview: str
