# Stubs for github.GitAuthor (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class GitAuthor(github.GithubObject.NonCompletableGithubObject):
    @property
    def date(self): ...
    @property
    def email(self): ...
    @property
    def name(self): ...
