# Stubs for github.GitBlob (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class GitBlob(github.GithubObject.CompletableGithubObject):
    @property
    def content(self): ...
    @property
    def encoding(self): ...
    @property
    def sha(self): ...
    @property
    def size(self): ...
    @property
    def url(self): ...
