# Stubs for github.GitignoreTemplate (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class GitignoreTemplate(github.GithubObject.NonCompletableGithubObject):
    @property
    def source(self): ...
    @property
    def name(self): ...
