# Stubs for github.GitObject (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class GitObject(github.GithubObject.NonCompletableGithubObject):
    @property
    def sha(self): ...
    @property
    def type(self): ...
    @property
    def url(self): ...
