# Stubs for github.GitTree (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GitTreeElement

class GitTree(github.GithubObject.CompletableGithubObject):
    @property
    def sha(self): ...
    @property
    def tree(self): ...
    @property
    def url(self): ...
