# Stubs for github.HookResponse (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class HookResponse(github.GithubObject.NonCompletableGithubObject):
    @property
    def code(self): ...
    @property
    def message(self): ...
    @property
    def status(self): ...
