# Stubs for github.HookDescription (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class HookDescription(github.GithubObject.NonCompletableGithubObject):
    @property
    def events(self): ...
    @property
    def name(self): ...
    @property
    def schema(self): ...
    @property
    def supported_events(self): ...
