# Stubs for github.InputGitAuthor (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class InputGitAuthor:
    def __init__(self, name: Any, email: Any, date: Any = ...) -> None: ...
