# Stubs for github.InputGitTreeElement (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class InputGitTreeElement:
    def __init__(self, path: Any, mode: Any, type: Any, content: Any = ..., sha: Any = ...) -> None: ...
