# Stubs for github.InputFileContent (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class InputFileContent:
    def __init__(self, content: Any, new_name: Any = ...) -> None: ...
