# Stubs for github.InstallationAuthorization (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.NamedUser

class InstallationAuthorization(github.GithubObject.NonCompletableGithubObject):
    @property
    def token(self): ...
    @property
    def expires_at(self): ...
    @property
    def on_behalf_of(self): ...
