# Stubs for github.IssuePullRequest (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class IssuePullRequest(github.GithubObject.NonCompletableGithubObject):
    @property
    def diff_url(self): ...
    @property
    def html_url(self): ...
    @property
    def patch_url(self): ...
