# Stubs for github.NotificationSubject (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class NotificationSubject(github.GithubObject.NonCompletableGithubObject):
    @property
    def title(self): ...
    @property
    def url(self): ...
    @property
    def latest_comment_url(self): ...
    @property
    def type(self): ...
