# Stubs for github.Path (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class Path(github.GithubObject.NonCompletableGithubObject):
    @property
    def path(self): ...
    @property
    def title(self): ...
    @property
    def count(self): ...
    @property
    def uniques(self): ...
