# Stubs for github.Permissions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class Permissions(github.GithubObject.NonCompletableGithubObject):
    @property
    def admin(self): ...
    @property
    def pull(self): ...
    @property
    def push(self): ...
