# Stubs for github.Plan (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class Plan(github.GithubObject.NonCompletableGithubObject):
    @property
    def collaborators(self): ...
    @property
    def name(self): ...
    @property
    def private_repos(self): ...
    @property
    def space(self): ...
