# Stubs for github.PullRequestPart (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.NamedUser

class PullRequestPart(github.GithubObject.NonCompletableGithubObject):
    @property
    def label(self): ...
    @property
    def ref(self) -> str: ...
    @property
    def repo(self): ...
    @property
    def sha(self): ...
    @property
    def user(self): ...
