# Stubs for github.PullRequestMergeStatus (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class PullRequestMergeStatus(github.GithubObject.NonCompletableGithubObject):
    @property
    def merged(self): ...
    @property
    def message(self): ...
    @property
    def sha(self): ...
