# Stubs for github.RateLimit (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.Rate

class RateLimit(github.GithubObject.NonCompletableGithubObject):
    @property
    def rate(self): ...
    @property
    def core(self): ...
    @property
    def search(self): ...
    @property
    def graphql(self): ...
