# Stubs for github.Rate (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class Rate(github.GithubObject.NonCompletableGithubObject):
    @property
    def limit(self): ...
    @property
    def remaining(self): ...
    @property
    def reset(self): ...
