# Stubs for github.Referrer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class Referrer(github.GithubObject.NonCompletableGithubObject):
    @property
    def referrer(self): ...
    @property
    def count(self): ...
    @property
    def uniques(self): ...
