# Stubs for github.RequiredStatusChecks (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class RequiredStatusChecks(github.GithubObject.CompletableGithubObject):
    @property
    def strict(self): ...
    @property
    def contexts(self): ...
    @property
    def url(self): ...
