# Stubs for github.Stargazer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github

class Stargazer(github.GithubObject.NonCompletableGithubObject):
    @property
    def starred_at(self): ...
    @property
    def user(self): ...
