# Stubs for github.StatsPunchCard (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.NamedUser
from typing import Any

class StatsPunchCard(github.GithubObject.NonCompletableGithubObject):
    def get(self, day: Any, hour: Any): ...
