# Stubs for github.StatsCodeFrequency (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class StatsCodeFrequency(github.GithubObject.NonCompletableGithubObject):
    @property
    def week(self): ...
    @property
    def additions(self): ...
    @property
    def deletions(self): ...
