# Stubs for github.StatsParticipation (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.NamedUser

class StatsParticipation(github.GithubObject.NonCompletableGithubObject):
    @property
    def all(self): ...
    @property
    def owner(self): ...
