# Stubs for github.StatsCommitActivity (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class StatsCommitActivity(github.GithubObject.NonCompletableGithubObject):
    @property
    def week(self): ...
    @property
    def total(self): ...
    @property
    def days(self): ...
