# Stubs for github.Topic (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class Topic(github.GithubObject.CompletableGithubObject):
    @property
    def name(self): ...
    @property
    def display_name(self): ...
    @property
    def short_description(self): ...
    @property
    def description(self): ...
