# Stubs for github.View (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import github.GithubObject

class View(github.GithubObject.NonCompletableGithubObject):
    @property
    def timestamp(self): ...
    @property
    def count(self): ...
    @property
    def uniques(self): ...
