# Stubs for hqlib.metric_source.abstract.team_spirit (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ... import domain

class TeamSpirit(domain.MetricSource):
    metric_source_name: str = ...
    def team_spirit(self, team_id: str) -> str: ...
