# Stubs for hqlib.metric_source.abstract.user_story_points_predictor (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ... import domain

class UserStoryPointsPredictor(domain.MetricSource):
    metric_source_name: str = ...
    def predicted_number_of_user_story_points(self, *metric_source_ids: str) -> float: ...
    def planned_number_of_user_story_points(self, *metric_source_ids: str) -> float: ...
