# Stubs for urlmatch.urlmatch (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Sequence, Union

class BadMatchPattern(Exception): ...

def parse_match_pattern(pattern: str, path_required: bool = ..., fuzzy_scheme: bool = ..., http_auth_allowed: bool = ...) -> str: ...
def urlmatch(match_pattern: Union[Sequence[str], str], url: str, **kwargs: Any) -> bool: ...
