# Stubs for hqlib.metric.environment.ci_jobs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from hqlib.domain import LowerIsBetterMetric
from typing import Any

class CIJobs(LowerIsBetterMetric):
    metric_source_class: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def convert_item_to_extra_info(item: Any): ...
