# Stubs for hqlib.metric_source (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .abstract.backlog import Backlog as Backlog
from .abstract.ci_server import CIServer as CIServer
from .abstract.coverage_report import ARTCoverageReport as ARTCoverageReport, AggregatedCoverageReport as AggregatedCoverageReport, UnittestCoverageReport as UnittestCoverageReport
from .abstract.issue_log import ActionLog as ActionLog, IssueLog as IssueLog, RiskLog as RiskLog
from .abstract.issue_tracker import BugTracker as BugTracker, FindingTracker as FindingTracker, ManualLogicalTestCaseTracker as ManualLogicalTestCaseTracker, QualityGateTracker as QualityGateTracker, ReadyUserStoryPointsTracker as ReadyUserStoryPointsTracker, SecurityBugTracker as SecurityBugTracker, StaticSecurityBugTracker as StaticSecurityBugTracker, TechnicalDebtTracker as TechnicalDebtTracker, UserStoriesDurationTracker as UserStoriesDurationTracker, UserStoriesInProgressTracker as UserStoriesInProgressTracker, UserStoryWithoutPerformanceRiskAssessmentTracker as UserStoryWithoutPerformanceRiskAssessmentTracker, UserStoryWithoutSecurityRiskAssessmentTracker as UserStoryWithoutSecurityRiskAssessmentTracker
from .abstract.owasp_dependency_report import Dependency as Dependency, OWASPDependencyReport as OWASPDependencyReport
from .abstract.performance_report import PerformanceEnduranceTestReport as PerformanceEnduranceTestReport, PerformanceLoadTestReport as PerformanceLoadTestReport, PerformanceScalabilityTestReport as PerformanceScalabilityTestReport
from .abstract.team_spirit import TeamSpirit as TeamSpirit
from .abstract.test_report import SystemTestReport as SystemTestReport, TestReport as TestReport, UnitTestReport as UnitTestReport
from .abstract.user_story_points_predictor import UserStoryPointsPredictor as UserStoryPointsPredictor
from .abstract.version_control_system import Branch as Branch, VersionControlSystem as VersionControlSystem
from .axe import AxeReport as AxeReport
from .birt import Birt as Birt
from .checkmarx import Checkmarx as Checkmarx
from .ci_server.gitlab import GitLabCI as GitLabCI
from .ci_server.jenkins import Jenkins as Jenkins
from .coverage_report.jacoco import JaCoCo as JaCoCo
from .coverage_report.lcov import LCOV as LCOV
from .coverage_report.ncover import NCover as NCover
from .file.file_with_date import FileWithDate as FileWithDate
from .history import CompactHistory as CompactHistory, History as History
from .issue_log.jira_action_list import JiraActionList as JiraActionList
from .issue_log.sharepoint_planner import SharepointPlanner as SharepointPlanner
from .issue_log.trello import TrelloBoard as TrelloBoard
from .issue_log.wekan import WekanBoard as WekanBoard
from .issue_tracker.jira_filter import JiraFilter as JiraFilter
from .jira import Jira as Jira
from .jira_backlog import JiraBacklog as JiraBacklog
from .ojaudit import OJAuditReport as OJAuditReport
from .open_vas_scan_report import OpenVASScanReport as OpenVASScanReport
from .owasp_dependency_report.jenkins_owasp_dependency_plugin import JenkinsOWASPDependencyReport as JenkinsOWASPDependencyReport
from .owasp_dependency_report.owasp_dependency_xml_report import OWASPDependencyXMLReport as OWASPDependencyXMLReport
from .owasp_dependency_report.tfs_owasp_dependency_xml_report import TfsOWASPDependencyXMLReport as TfsOWASPDependencyXMLReport
from .performance_report.ictu_performancereport import ICTUPerformanceEnduranceTestReport as ICTUPerformanceEnduranceTestReport, ICTUPerformanceLoadTestReport as ICTUPerformanceLoadTestReport, ICTUPerformanceScalabilityTestReport as ICTUPerformanceScalabilityTestReport
from .performance_report.spirit_splunk_csv import SpiritSplunkCSVPerformanceEnduranceTestReport as SpiritSplunkCSVPerformanceEnduranceTestReport, SpiritSplunkCSVPerformanceLoadTestReport as SpiritSplunkCSVPerformanceLoadTestReport, SpiritSplunkCSVPerformanceScalabilityTestReport as SpiritSplunkCSVPerformanceScalabilityTestReport
from .sonar import Sonar as Sonar, Sonar6 as Sonar6, Sonar7 as Sonar7, extract_branch_decorator as extract_branch_decorator
from .team_spirit.happiness import Happiness as Happiness
from .team_spirit.wiki import Wiki as Wiki
from .test_report.bamboo_test_report import BambooTestReport as BambooTestReport
from .test_report.jenkins_test_report import JenkinsTestReport as JenkinsTestReport
from .test_report.junit_test_report import JunitTestReport as JunitTestReport
from .test_report.robot_framework_test_report import RobotFrameworkTestReport as RobotFrameworkTestReport
from .test_report.testng_test_report import TestNGTestReport as TestNGTestReport
from .test_report.uft_test_report import UFTTestReport as UFTTestReport
from .url_opener import UrlOpener as UrlOpener
from .user_story_points_predictor.gros_user_story_points_predictor import GROSUserStoryPointsPredictor as GROSUserStoryPointsPredictor
from .version_control_system.git import Git as Git
from .version_control_system.subversion import Subversion as Subversion
from .zap_scan_report import ZAPScanReport as ZAPScanReport
