# Stubs for hqlib.metric_source.beautifulsoup (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from . import url_opener
from typing import Any, Callable

class BeautifulSoupOpener(url_opener.UrlOpener):
    def soup(self, url: str) -> Callable[..., Any]: ...
