# Stubs for hqlib.domain (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import DomainObject as DomainObject
from .measurement.directed_metric import HigherIsBetterMetric as HigherIsBetterMetric, LowerIsBetterMetric as LowerIsBetterMetric
from .measurement.metric import ExtraInfo as ExtraInfo, Metric as Metric
from .measurement.metric_source import MetricSource as MetricSource
from .measurement.metric_source_age_metric import MetricSourceAgeMetric as MetricSourceAgeMetric
from .measurement.metric_source_with_issues import MetricSourceWithIssues as MetricSourceWithIssues
from .measurement.percentage_metric import HigherPercentageIsBetterMetric as HigherPercentageIsBetterMetric, LowerPercentageIsBetterMetric as LowerPercentageIsBetterMetric, PercentageMetric as PercentageMetric
from .measurement.target import AdaptedTarget as AdaptedTarget, DynamicTechnicalDebtTarget as DynamicTechnicalDebtTarget, TechnicalDebtTarget as TechnicalDebtTarget
from .software_development.document import Document as Document
from .software_development.environment import Environment as Environment
from .software_development.process import IssueManagement as IssueManagement, Process as Process, ProjectManagement as ProjectManagement, Scrum as Scrum
from .software_development.product import Application as Application, Component as Component, Product as Product
from .software_development.project import Project as Project
from .software_development.requirement import Requirement as Requirement, RequirementSubject as RequirementSubject
from .software_development.team import Team as Team
