# Stubs for svn.common_base (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, List, Optional, Union

class CommonBase:
    def external_command(self, cmd: Any, success_code: int = ..., do_combine: bool = ..., return_binary: bool = ..., environment: Any = ..., wd: Optional[Any] = ...) -> Union[bytes, List[str]]: ...
    def rows_to_dict(self, rows: Any, lc: bool = ...): ...
