# Stubs for svn.constants (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

K_DIR: str
K_FILE: str
LT_URL: str
LT_PATH: str
ST_ADDED: int
ST_CONFLICTED: int
ST_DELETED: int
ST_EXTERNAL: int
ST_IGNORED: int
ST_INCOMPLETE: int
ST_MERGED: int
ST_MISSING: int
ST_MODIFIED: int
ST_NONE: int
ST_NORMAL: int
ST_OBSTRUCTED: int
ST_REPLACED: int
ST_UNVERSIONED: int
STATUS_TYPE_LOOKUP: Any
