# Stubs for svn.utility (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def get_client(url_or_path: Any, *args: Any, **kwargs: Any): ...
