# Stubs for jira (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from jira.client import JIRA as JIRA
from jira.resources import Comment as Comment, Issue as Issue, Priority as Priority, Project as Project, Role as Role, User as User, Watchers as Watchers, Worklog as Worklog
from jira.config import get_jira as get_jira
from jira.exceptions import JIRAError as JIRAError
from typing import Any

version_info: Any

# Names in __all__ with no definition:
#   __version__
