# Stubs for jira.config (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def get_jira(profile: Optional[Any] = ..., url: str = ..., username: str = ..., password: str = ..., appid: Optional[Any] = ..., autofix: bool = ..., verify: bool = ...): ...
