name: grip-on-software/data-gathering
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: "${{ matrix.python }}"
      - name: Install development packages for some stale dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-dev libxslt1-dev
      - name: Install dependencies for test
        run: |
          pip install -r requirements-test.txt
          pip install coveralls
      - name: Unit test and coverage
        run: |
          coverage run tests.py
          coverage xml -i --include=gatherer/*
      - name: Adjust source paths in coverage for Sonar
        run: sed -i "s/<source>\/home\/runner\/work\/data-gathering\/data-gathering/<source>\/github\/workspace/g" /home/runner/work/data-gathering/data-gathering/coverage.xml
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.1.1
        env:
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - run: coveralls
        if: "${{ success() }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    strategy:
      matrix:
        python:
        - '3.8.18'
